---
all:
  children:
    full:
      children:
        ubuntu:
          hosts:
            ubuntu-24:
              ansible_host: 172.24.24.170
            asnv:
              ansible_host: 82.99.202.245
              ansible_user: sysadmin
            ntp1.fanhab.ir:
              ansible_host: 172.20.51.1
            ntp2.fanhab.ir:
              ansible_host: 172.20.51.2
            Splunk-SH.fanhab.ir :
              ansible_host: 172.20.15.50
            Splunk-LM.fanhab.ir:
              ansible_host: 172.20.15.49

        redhat:
          hosts:
            mc.tbn.dc:
              ansible_host: 172.23.23.20
            rocky-9:
              ansible_host: 172.24.24.171

